workflows:
  rf-tests:
    name: Robot Framework mobile tests
    instance_type: linux
    scripts:
      - name: Install Appium
        script: npm install --location=global appium
      - name: Install Robot Framework
        script: pip install robotframework robotframework-appiumlibrary
      - name: Launch emulator
        script: |
          cd /usr/local/android/sdk//tools
          emulator -avd emulator &
          adb wait-for-device
      - name: Test
        script: |
          robot --outputDir rf-results tests
          adb logcat -d > emulator.log
          cp  -r rf-results $CM_EXPORT_DIR/rf-results
          cp emulator.log $CM_EXPORT_DIR/
